# Generated by Django 5.0 on 2023-12-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_price_assistance', '0004_predictpricemodel_needelevator'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictpricemodel',
            name='needParking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictpricemodel',
            name='needWareHouse',
            field=models.BooleanField(default=False),
        ),
    ]
