# Generated by Django 5.0 on 2023-12-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_price_assistance', '0005_predictpricemodel_needparking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictpricemodel',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
