# Generated by Django 5.0 on 2023-12-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_price_assistance', '0006_predictpricemodel_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictpricemodel',
            name='bookmarked',
        ),
    ]
