# Generated by Django 5.0 on 2023-12-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_price_assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictpricemodel',
            name='predict_price',
            field=models.IntegerField(),
        ),
    ]
