# Generated by Django 5.0 on 2023-12-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_price_assistance', '0003_alter_predictpricemodel_predict_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictpricemodel',
            name='needElevator',
            field=models.BooleanField(default=False),
        ),
    ]
